# Generated by Django 6.0.5 on 2026-05-25 10:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=160)),
                ('categoria', models.CharField(blank=True, max_length=90)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado')], default='pendente', max_length=20)),
                ('forma_pagamento', models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('boleto', 'Boleto'), ('cartao', 'Cartao'), ('transferencia', 'Transferencia'), ('outro', 'Outro')], default='pix', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('pendente', 'Pendente de assinatura'), ('assinado', 'Assinado'), ('vencido', 'Vencido')], default='pendente', max_length=20)),
                ('data_limite', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='crm.cliente')),
            ],
            options={
                'ordering': ['status', 'data_limite', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_lead', models.CharField(max_length=160)),
                ('titulo', models.CharField(max_length=160)),
                ('tipo_evento', models.CharField(blank=True, max_length=100)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('etapa', models.CharField(choices=[('novo', 'Novo lead'), ('orcamento', 'Orcamento'), ('negociacao', 'Negociacao'), ('fechado', 'Fechado'), ('perdido', 'Perdido')], default='novo', max_length=20)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=20)),
                ('origem', models.CharField(blank=True, max_length=90)),
                ('proximo_contato', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='crm.cliente')),
            ],
            options={
                'ordering': ['etapa', '-valor_estimado', 'nome_lead'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('trabalho', 'Trabalho'), ('tarefa', 'Tarefa'), ('pagamento', 'Pagamento'), ('reuniao', 'Reuniao'), ('entrega', 'Entrega'), ('lembrete', 'Lembrete')], default='tarefa', max_length=20)),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluida'), ('atrasada', 'Atrasada')], default='pendente', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='crm.cliente')),
            ],
            options={
                'ordering': ['data', 'hora', 'titulo'],
            },
        ),
    ]
