# Generated by Django 6.0.5 on 2026-05-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_despesa_documento_oportunidade_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='assinado_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='contato_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='documento',
            name='contato_whatsapp',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='documento',
            name='conteudo_contrato',
            field=models.TextField(blank=True, default='CONTRATO DE PRESTACAO DE SERVICOS FOTOGRAFICOS\n\nCliente: {{ cliente_nome }}\nContato: {{ cliente_contato }}\nServico contratado: {{ servico }}\nValor: R$ {{ valor }}\nData do evento: {{ data_evento }}\n\nO presente contrato define prazos, entrega dos arquivos, forma de pagamento e autorizacao de uso de imagem conforme combinado entre as partes.\n\nAssinatura do cliente: ______________________________\nAssinatura do fotografo: ____________________________'),
        ),
        migrations.AddField(
            model_name='documento',
            name='enviado_em',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='forma_envio',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('ambos', 'WhatsApp e e-mail')], default='whatsapp', max_length=20),
        ),
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado para assinatura'), ('pendente', 'Pendente de assinatura'), ('assinado', 'Assinado'), ('vencido', 'Vencido')], default='pendente', max_length=20),
        ),
    ]
