# Generated by Django 6.0.5 on 2026-05-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_documento_assinado_em_documento_contato_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='ultimo_envio_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='ultimo_envio_retorno',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='ultimo_envio_sucesso',
            field=models.BooleanField(default=False),
        ),
    ]
