# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_documento_ultimo_envio_em_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oportunidade",
            name="contato",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="oportunidade",
            name="data_festa",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oportunidade",
            name="horario",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
