# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_oportunidade_data_festa_horario_contato"),
    ]

    operations = [
        migrations.AddField(
            model_name="oportunidade",
            name="nome_indicacao",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
