# Generated by Codex on 2026-05-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_oportunidade_nome_indicacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=160)),
                ("tipo_evento", models.CharField(blank=True, max_length=100)),
                ("data_festa", models.DateField(blank=True, null=True)),
                ("horario", models.TimeField(blank=True, null=True)),
                ("contato", models.CharField(blank=True, max_length=80)),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos",
                        to="crm.cliente",
                    ),
                ),
            ],
            options={
                "ordering": ["data_festa", "horario", "nome"],
            },
        ),
        migrations.CreateModel(
            name="OportunidadePerdida",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=160)),
                ("tipo_prospeccao", models.CharField(blank=True, max_length=160)),
                ("nome_indicacao", models.CharField(blank=True, max_length=160)),
                ("tipo_evento", models.CharField(blank=True, max_length=100)),
                ("data_festa", models.DateField(blank=True, null=True)),
                ("horario", models.TimeField(blank=True, null=True)),
                ("contato", models.CharField(blank=True, max_length=80)),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "oportunidade",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registro_perdido",
                        to="crm.oportunidade",
                    ),
                ),
            ],
            options={
                "ordering": ["-atualizado_em", "nome"],
            },
        ),
    ]
