# Generated by Codex on 2026-05-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_evento_oportunidadeperdida"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="forma_pagamento",
            field=models.CharField(
                choices=[
                    ("pix", "Pix"),
                    ("dinheiro", "Dinheiro"),
                    ("boleto", "Boleto"),
                    ("cartao", "Cartao"),
                    ("transferencia", "Transferencia"),
                    ("outro", "Outro"),
                ],
                default="pix",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="valor_cobrado",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="evento",
            name="venda",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evento",
                to="crm.venda",
            ),
        ),
    ]
