# Generated by Codex on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_evento_valor_cobrado_forma_pagamento_venda"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="pagamento_recebido",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evento",
            name="quantidade_parcelas",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
