# Generated by Codex on 2026-05-27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0009_evento_pagamento_recebido_quantidade_parcelas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evento",
            name="tipo_evento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("casamento", "Casamento"),
                    ("pre_wedding", "Pre-wedding"),
                    ("ensaio_casal", "Ensaio de casal"),
                    ("ensaio_familia", "Ensaio de familia"),
                    ("gestante", "Gestante"),
                    ("newborn", "Newborn"),
                    ("acompanhamento_bebe", "Acompanhamento de bebe"),
                    ("batizado", "Batizado"),
                    ("aniversario", "Aniversario"),
                    ("aniversario_infantil", "Aniversario infantil"),
                    ("debutante", "15 anos / debutante"),
                    ("formatura", "Formatura"),
                    ("corporativo", "Corporativo"),
                    ("evento_social", "Evento social"),
                    ("evento_religioso", "Evento religioso"),
                    ("ensaio_feminino", "Ensaio feminino"),
                    ("ensaio_masculino", "Ensaio masculino"),
                    ("retrato_profissional", "Retrato profissional"),
                    ("branding", "Branding pessoal"),
                    ("produto", "Produto"),
                    ("imobiliario", "Imobiliario"),
                    ("esportivo", "Esportivo"),
                    ("pet", "Pet"),
                    ("outro", "Outro"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="LembreteAnual",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=160)),
                ("contato", models.CharField(blank=True, max_length=80)),
                ("data_original", models.DateField()),
                ("data_proximo_evento", models.DateField()),
                ("data_alerta", models.DateField()),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lembretes_anuais",
                        to="crm.cliente",
                    ),
                ),
                (
                    "evento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lembrete_anual",
                        to="crm.evento",
                    ),
                ),
            ],
            options={
                "ordering": ["data_alerta", "nome"],
            },
        ),
    ]
