# Generated by Codex on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_evento_tipo_choices_lembreteanual"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="primeira_parcela",
            field=models.DateField(blank=True, null=True),
        ),
    ]
