# Generated by Codex on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0011_evento_primeira_parcela"),
    ]

    operations = [
        migrations.AddField(
            model_name="oportunidade",
            name="valor_negociado",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
