# Generated by Django 5.2.14 on 2026-05-29 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_evento_local_evento_em_buffet'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='arquivo_assinado',
            field=models.FileField(blank=True, upload_to='documentos/assinados/'),
        ),
        migrations.AddField(
            model_name='documento',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='crm.evento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='conteudo_contrato',
            field=models.TextField(blank=True, default='CONTRATO DE SERVICO\n\nCONTRATADO: JOAO BOSCO FOTOGRAFIA\nE-MAIL: JOAOBOSCOFOTOS@GMAIL.COM\nTEL: (85) 98713-7641\nCNPJ: 25.165.098/0001-68\n\nCONTRATANTE: {{ cliente_nome }}\nCPF: {{ cliente_cpf }}\nENDERECO: {{ cliente_endereco }}\nTELEFONE: {{ cliente_telefone }}\nE-MAIL: {{ cliente_email }}\n\nNOME DO ANIVERSARIANTE: {{ aniversariante }}\nIDADE: {{ idade }}\nLOCAL: {{ local_evento }}\nDATA: {{ data_evento }}\nHORARIO: {{ horario_inicio }} as {{ horario_fim }}\n\nDESCRICAO DO SERVICO:\n{{ servico }}\n\nVALOR TOTAL: R$ {{ valor }}\nFORMA DE PAGAMENTO: {{ forma_pagamento }}\nPARCELAS:\n{{ parcelas }}\n\nADIANTAMENTO: R$ {{ adiantamento }}\nRESTANTE: R$ {{ restante }}\n\nOBS: PERMANENCIA DE ATE 03 HORAS NO EVENTO, INICIANDO A PARTIR DO HORARIO ESTABELECIDO ACIMA.\n\nSera executado um numero superior ao das fotos acima encomendadas, a fim de aumentar a opcao de escolha.\n\nO CONTRATADO entregara o LINK com todas as fotos do evento para a escolha das imagens que irao para o album no prazo de 20 (vinte) dias uteis apos o evento. O CONTRATANTE tera o prazo de 10 (dez) dias uteis, apos o recebimento das provas, para informar ao CONTRATADO as fotos selecionadas para o album.\n\nO CONTRATANTE tera um prazo de 12 meses, a contar a partir do recebimento das imagens, para informar a selecao de fotos que irao para o album. Caso ultrapasse o periodo estipulado, o valor sera reajustado de acordo com a tabela atual de precos.\n\nO CONTRATANTE devera enviar, em documento escrito, para o CONTRATADO, a lista de fotos escolhidas, utilizando a numeracao e nomenclatura original dos arquivos de prova.\n\nO CONTRATADO entregara os trabalhos, apos o evento, de acordo com as datas que seguem: fotos em LINK em 20 (vinte) dias uteis, sendo um LINK com 100 fotos tratadas e outro LINK com todas as imagens em alta resolucao; album em 45 (quarenta e cinco) dias uteis apos a devolucao das fotos ou projeto escolhido e aprovado pelo cliente.\n\nApos a entrega para verificacao e aprovacao do cliente, o mesmo tera 02 (dois) dias uteis para devolucao no caso de necessidade de correcao do projeto. Caso nao aconteca a devolucao no prazo estipulado, o produto final sera considerado aprovado pelo cliente.\n\nO LINK com fotos em alta resolucao pertence a empresa, ficando a disposicao para novas reproducoes mediante remuneracao estabelecida entre cliente e empresa.\n\nOs arquivos originais ficarao na empresa por 30 dias apos finalizar o contrato com o contratante.\n\nEm caso de desistencia, nao sera devolvido o adiantamento pago.\n\nO CONTRATANTE autoriza a utilizacao de sua imagem pelo CONTRATADO em seu portfolio ou redes sociais exclusivamente para fins de divulgacao de seu trabalho e sem fins comerciais.\n\n(    ) SIM         (    ) NAO\n\nE por estarem justos e contratados, firmam o presente instrumento em duas vias iguais.\n\nFortaleza, {{ data_contrato }}\n\nASSINATURA DO CLIENTE: __________________________________________\nJOAO BOSCO LISBOA DE MORAIS: ___________________________________\n\nEste PDF deve ser assinado digitalmente pelo cliente no Assinador gov.br e reenviado para anexo no cadastro do evento.\n'),
        ),
    ]
