# Generated by Django 5.2.14 on 2026-05-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_documento_conteudo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='forma_envio',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('ambos', 'WhatsApp e e-mail')], default='ambos', max_length=20),
        ),
    ]
