# Generated by Django 5.2.14 on 2026-05-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_alter_documento_forma_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado para assinatura'), ('pendente', 'Pendente de assinatura'), ('assinado', 'Assinado'), ('vencido', 'Vencido')], default='rascunho', max_length=20),
        ),
    ]
