# Generated by Codex on 2026-05-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0018_alter_documento_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="adiantamento",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="evento",
            name="aniversariante",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="evento",
            name="autoriza_uso_imagem",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="cpf_contratante",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="evento",
            name="descricao_servico",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="endereco_contratante",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="evento",
            name="horario_fim",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="idade",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
