# Generated by Codex on 2026-05-30

from django.db import migrations, models

from crm.models import CONTRATO_FESTA_INFANTIL_TEMPLATE


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0019_evento_dados_contrato"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="conteudo_contrato",
            field=models.TextField(blank=True, default=CONTRATO_FESTA_INFANTIL_TEMPLATE),
        ),
    ]
