# Generated by Django 5.2.14 on 2026-06-09 13:39

from django.db import migrations, models


def marcar_adiantamentos_existentes(apps, schema_editor):
    Evento = apps.get_model("crm", "Evento")
    Evento.objects.filter(adiantamento__gt=0).update(adiantamento_pago=True)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_seed_auth_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='adiantamento_pago',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(marcar_adiantamentos_existentes, migrations.RunPython.noop),
    ]
