# Generated by Django 5.2.14 on 2026-06-09 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_contratoadminempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCompromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('reuniao', 'Reuniao'), ('cobranca', 'Cobranca'), ('suporte', 'Suporte'), ('tarefa', 'Tarefa')], default='tarefa', max_length=20)),
                ('data', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('concluida', 'Concluida'), ('atrasada', 'Atrasada')], default='pendente', max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compromissos_admin', to='crm.empresa')),
            ],
            options={
                'ordering': ['data', 'hora', 'titulo'],
            },
        ),
    ]
