# Generated by Django 5.2.14 on 2026-06-09 14:27

import django.db.models.deletion
from django.db import migrations, models


def vincular_dados_existentes(apps, schema_editor):
    Empresa = apps.get_model("crm", "Empresa")
    empresa, _ = Empresa.objects.get_or_create(
        nome="Joao Bosco Fotografia",
        defaults={"email": "joaoboscofotos@gmail.com", "telefone": "(85) 98713-7641"},
    )
    for model_name in [
        "Cliente",
        "Venda",
        "Despesa",
        "Oportunidade",
        "OportunidadePerdida",
        "Evento",
        "LembreteAnual",
        "Tarefa",
        "Documento",
    ]:
        Model = apps.get_model("crm", model_name)
        Model.objects.filter(empresa__isnull=True).update(empresa=empresa)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_admincompromisso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='crm.empresa'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='crm.empresa'),
        ),
        migrations.AddField(
            model_name='documento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='crm.empresa'),
        ),
        migrations.AddField(
            model_name='evento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='crm.empresa'),
        ),
        migrations.AddField(
            model_name='lembreteanual',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lembretes_anuais', to='crm.empresa'),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='crm.empresa'),
        ),
        migrations.AddField(
            model_name='oportunidadeperdida',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades_perdidas', to='crm.empresa'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='crm.empresa'),
        ),
        migrations.AddField(
            model_name='venda',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='crm.empresa'),
        ),
        migrations.RunPython(vincular_dados_existentes, migrations.RunPython.noop),
    ]
