# Generated by Django 5.2.14 on 2026-07-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_cliente_empresa_despesa_empresa_documento_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='nome_contato',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
